apiVersion: apps/v1
kind: Service
metadata:
  name: hello-service
  labels:
    run: hello-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: hello-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellospring-deployment
  labels:
    app: hellospring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellospring
      run: hello-service
  template:
    metadata:
      labels:
        app: hellospring
    spec:
      containers:
      - name: hellospring
        image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_NUMBER}
        ports:
        - containerPort: 8080
        env:
          - name: SECRET
            value: "I'm a secret"
          - name: NOT_SECRET
            value: "I'm not a secret"
